# Generated by Django 4.2.1 on 2023-05-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree',
            new_name='Rocket',
        ),
    ]
