# Generated by Django 4.2.1 on 2023-06-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_tree_rocket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rocket',
            new_name='Launch',
        ),
    ]
