# Generated by Django 4.2.1 on 2023-06-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_rocket_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='date',
            field=models.DateField(),
        ),
    ]
