# Generated by Django 4.2.1 on 2023-06-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_launch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('schedule', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('D', 'Dusk')], default='M', max_length=1)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.launch')),
            ],
        ),
    ]
