# Generated by Django 4.2.1 on 2023-06-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_satellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='color',
        ),
    ]
