# Generated by Django 4.2.1 on 2023-06-03 04:40

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_satellite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='color',
            field=models.CharField(default=main_app.models.get_random_color, max_length=20),
        ),
    ]
